services:
  api:
    image: console-api:${API_TAG:-latest}
    build:
      dockerfile: docker/Dockerfile.node
      target: production-nginx
      args:
        WORKSPACE: apps/api

  indexer:
    image: console-indexer:${INDEXER_TAG:-latest}
    build:
      dockerfile: docker/Dockerfile.node
      target: production
      args:
        WORKSPACE: apps/indexer

  provider-proxy:
    image: console-provider-proxy:${PROVIDER_PROXY_TAG:-latest}
    build:
      dockerfile: docker/Dockerfile.node
      target: production-nginx
      args:
        WORKSPACE: apps/provider-proxy

  deploy-web:
    image: console-deploy-web:${DEPLOY_WEB_TAG:-latest}
    build:
      dockerfile: docker/Dockerfile.nextjs
      target: production-nginx
      args:
        WORKSPACE: apps/deploy-web

  stats-web:
    image: console-stats-web:${STATS_WEB_TAG:-latest}
    build:
      dockerfile: docker/Dockerfile.nextjs
      target: production
      args:
        WORKSPACE: apps/stats-web

  provider-console:
    image: arc10/provider-console:${PROVIDER_CONSOLE_TAG:-latest}
    build:
      dockerfile: docker/Dockerfile.nextjs
      platforms:
        - "linux/amd64"
      target: production
      args:
        WORKSPACE: apps/provider-console
