name: Triggers coverage check for files that do not require coverage

on:
  pull_request:
    branches: ["main", "main-sdk-next"]
    paths-ignore:
      - 'apps/**'
      - 'packages/**'

jobs:
  trigger-coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Check for changes
        uses: dorny/paths-filter@v3.0.2
        id: has_changes
        with:
          filters: |
            app:
              - 'apps/**'
              - 'packages/**'

      - uses: codecov/codecov-action@v5
        if: steps.has_changes.outputs.app != 'true'
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          run_command: empty-upload
